#!/bin/bash
# VNC xstartup script

# Unset SESSION_MANAGER to avoid issues
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start dbus
eval $(dbus-launch --sh-syntax)
export DBUS_SESSION_BUS_ADDRESS

# Set up environment
export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=XFCE
export XDG_CONFIG_HOME=/home/designer/.config

# Start XFCE
exec startxfce4
